rootProject.name = "gradle-tools"

// Gradle components
includeBuild("cores/artifactory-base")
includeBuild("cores/bitbucket-cloud-base")
includeBuild("cores/bitbucket-data-center-base")
includeBuild("cores/aws-codeartifact-java-base")
includeBuild("cores/aws-codeartifact-kotlin-base")
includeBuild("cores/aws-ecr-java-base")
includeBuild("cores/aws-ecr-kotlin-base")
includeBuild("cores/aws-imds-java-base")
includeBuild("cores/aws-imds-kotlin-base")
includeBuild("cores/aws-java-extensions")
includeBuild("cores/aws-kotlin-extensions")
includeBuild("cores/aws-kms-java-base")
includeBuild("cores/aws-kms-kotlin-base")
includeBuild("cores/aws-lambda-java-base")
includeBuild("cores/aws-lambda-kotlin-base")
includeBuild("cores/aws-s3-java-base")
includeBuild("cores/aws-s3-kotlin-base")
includeBuild("cores/aws-secrets-manager-java-base")
includeBuild("cores/aws-secrets-manager-kotlin-base")
includeBuild("cores/aws-ses-java-base")
includeBuild("cores/aws-ses-kotlin-base")
includeBuild("cores/aws-sns-java-base")
includeBuild("cores/aws-sns-kotlin-base")
includeBuild("cores/aws-sqs-java-base")
includeBuild("cores/aws-sqs-kotlin-base")
includeBuild("cores/aws-ssm-java-base")
includeBuild("cores/aws-ssm-kotlin-base")
includeBuild("cores/aws-sts-java-base")
includeBuild("cores/aws-sts-kotlin-base")
includeBuild("cores/clients-base")
includeBuild("cores/dokka-dash")
includeBuild("cores/git-core")
includeBuild("cores/jfrog-cli-core")
includeBuild("cores/google-cloud-artifact-registry-base")
includeBuild("cores/google-cloud-pubsub-base")
includeBuild("cores/google-cloud-secret-manager-base")
includeBuild("cores/google-cloud-storage-base")
includeBuild("cores/gradle-extensions")

includeBuild("aggregation")
includeBuild("metadata")
