[libraries]
# BOMs
kotlin-gradle-plugins-bom = "org.jetbrains.kotlin:kotlin-gradle-plugins-bom:2.0.21"

# Internal
dependency-analysis-plugin = "com.autonomousapps:dependency-analysis-gradle-plugin:2.8.2"
detekt-plugin = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.23.7"
dokkatoo-plugin = "dev.adamko.dokkatoo:dokkatoo-plugin:2.4.0"
gradlex-dependency-conflict-resolution-plugin = "org.gradlex:jvm-dependency-conflict-resolution:2.1.2"
gradlex-reproducible-builds-plugin = "org.gradlex:reproducible-builds:1.0"
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
reckon-plugin = "org.ajoberstar.reckon:reckon-gradle:0.19.1"

# API Dependencies
jgit = "org.eclipse.jgit:org.eclipse.jgit:7.1.0.202411261347-r"
