package com.kelvsyc.gradle.google.cloud

import com.kelvsyc.gradle.clients.CredentialReference
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.Provider

/**
 * Configures these parameters to use [com.google.cloud.NoCredentials], i.e. no authentication.
 */
fun GcpBuildServiceParams.noCredentials() {
    credentialSource.set(GcpCredentialSource.NONE)
}

/**
 * Configures these parameters to use
 * [GoogleCredentials.getApplicationDefault][com.google.auth.oauth2.GoogleCredentials.getApplicationDefault],
 * which resolves credentials from `GOOGLE_APPLICATION_CREDENTIALS`, gcloud user credentials,
 * GCE/GKE/Cloud Run metadata, and other standard sources in order.
 */
fun GcpBuildServiceParams.applicationDefault() {
    credentialSource.set(GcpCredentialSource.APPLICATION_DEFAULT)
}

/**
 * Configures these parameters to load
 * [ServiceAccountCredentials][com.google.auth.oauth2.ServiceAccountCredentials] from the supplied
 * JSON key file.
 */
@JvmName("serviceAccountFromFile")
fun GcpBuildServiceParams.serviceAccount(file: Provider<RegularFile>) {
    credentialSource.set(GcpCredentialSource.SERVICE_ACCOUNT_JSON_FILE)
    credentialsFile.set(file)
}

/**
 * Configures these parameters to load
 * [ServiceAccountCredentials][com.google.auth.oauth2.ServiceAccountCredentials] from a service
 * account JSON key payload referenced by [json].
 *
 * The [json] reference points to an environment variable or system property whose value is the full
 * service account JSON string. By default, the `GOOGLE_APPLICATION_CREDENTIALS_JSON` environment
 * variable is used — a common convention in CI/CD systems where the key is stored as a secret.
 */
@JvmName("serviceAccountFromJson")
fun GcpBuildServiceParams.serviceAccount(
    json: CredentialReference = CredentialReference.EnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS_JSON"),
) {
    credentialSource.set(GcpCredentialSource.SERVICE_ACCOUNT_JSON_ENV)
    credentialsJsonRef.set(json)
}

/**
 * Configures these parameters to use a static OAuth2 access token referenced by [token], wrapped
 * in [GoogleCredentials.create][com.google.auth.oauth2.GoogleCredentials.create].
 *
 * The [token] reference points to an environment variable or system property whose value is the
 * token string. By default, the `GOOGLE_OAUTH2_TOKEN` environment variable is used.
 */
fun GcpBuildServiceParams.accessToken(
    token: CredentialReference = CredentialReference.EnvironmentVariable("GOOGLE_OAUTH2_TOKEN"),
) {
    credentialSource.set(GcpCredentialSource.ACCESS_TOKEN)
    accessTokenRef.set(token)
}

/**
 * Configures these parameters to load
 * [ExternalAccountCredentials][com.google.auth.oauth2.ExternalAccountCredentials] from the supplied
 * credential config JSON file.
 *
 * The file is typically generated by `gcloud iam workload-identity-pools create-cred-config` and
 * encodes the full Workload Identity Federation configuration, including optional service account
 * impersonation.
 */
@JvmName("externalAccountFromFile")
fun GcpBuildServiceParams.externalAccount(file: Provider<RegularFile>) {
    credentialSource.set(GcpCredentialSource.EXTERNAL_ACCOUNT_CONFIG_FILE)
    externalAccountConfigFile.set(file)
}

/**
 * Configures these parameters to load
 * [ExternalAccountCredentials][com.google.auth.oauth2.ExternalAccountCredentials] from a credential
 * config JSON payload referenced by [json].
 *
 * The [json] reference points to an environment variable or system property whose value is the full
 * credential config JSON string. By default, the `GOOGLE_EXTERNAL_ACCOUNT_CONFIG` environment
 * variable is used.
 */
@JvmName("externalAccountFromJson")
fun GcpBuildServiceParams.externalAccount(
    json: CredentialReference = CredentialReference.EnvironmentVariable("GOOGLE_EXTERNAL_ACCOUNT_CONFIG"),
) {
    credentialSource.set(GcpCredentialSource.EXTERNAL_ACCOUNT_CONFIG_ENV)
    externalAccountConfigRef.set(json)
}

/**
 * Configures these parameters to construct
 * [IdentityPoolCredentials][com.google.auth.oauth2.IdentityPoolCredentials] programmatically from
 * a pre-fetched OIDC [token] and workload identity pool provider [audience].
 *
 * The [token] reference points to an environment variable or system property whose value is the
 * OIDC token string, resolved lazily at token-refresh time. When [impersonateServiceAccount] is
 * set, the STS-exchanged token is further exchanged for a service account access token via the IAM
 * Credentials API automatically.
 *
 * @param audience Full pool provider resource name, e.g.
 *   `//iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID`
 * @param token Reference to the pre-fetched OIDC token
 * @param impersonateServiceAccount Email of the service account to impersonate, or `null` to use
 *   the STS token directly
 */
fun GcpBuildServiceParams.workloadIdentity(
    audience: String,
    token: CredentialReference,
    impersonateServiceAccount: String? = null,
) {
    credentialSource.set(GcpCredentialSource.WORKLOAD_IDENTITY_OIDC)
    workloadIdentityAudience.set(audience)
    workloadIdentityTokenRef.set(token)
    impersonateServiceAccount?.let { workloadIdentityServiceAccountEmail.set(it) }
}
