package com.kelvsyc.gradle.google.cloud

/**
 * Discriminator for which Google Cloud credentials object to construct from [GcpBuildServiceParams].
 *
 * Set via the extension functions on [GcpBuildServiceParams] rather than directly.
 */
enum class GcpCredentialSource {
    /**
     * Use [com.google.cloud.NoCredentials], i.e. no authentication.
     *
     * Useful for tests, local emulators (e.g. Pub/Sub emulator), and public-bucket access. Maps to
     * [com.google.api.gax.core.NoCredentialsProvider] when a `CredentialsProvider` is required.
     */
    NONE,

    /**
     * Use [com.google.auth.oauth2.GoogleCredentials.getApplicationDefault], which resolves
     * credentials from `GOOGLE_APPLICATION_CREDENTIALS`, gcloud user credentials, GCE/GKE/Cloud Run
     * metadata, and other standard sources in order.
     */
    APPLICATION_DEFAULT,

    /**
     * Load a [com.google.auth.oauth2.ServiceAccountCredentials] from the JSON key file at
     * [GcpBuildServiceParams.credentialsFile].
     */
    SERVICE_ACCOUNT_JSON_FILE,

    /**
     * Load a [com.google.auth.oauth2.ServiceAccountCredentials] from the JSON key payload referenced by
     * [GcpBuildServiceParams.credentialsJsonRef]. The reference points to an environment variable or system
     * property whose value is the full service account JSON string.
     */
    SERVICE_ACCOUNT_JSON_ENV,

    /**
     * Build a [com.google.auth.oauth2.GoogleCredentials] from a static OAuth2 access token referenced by
     * [GcpBuildServiceParams.accessTokenRef]. The reference points to an environment variable or system
     * property whose value is the token string.
     */
    ACCESS_TOKEN,

    /**
     * Load an [com.google.auth.oauth2.ExternalAccountCredentials] from the credential config JSON file at
     * [GcpBuildServiceParams.externalAccountConfigFile].
     *
     * The credential config JSON is generated by
     * `gcloud iam workload-identity-pools create-cred-config` and encodes the full federation
     * configuration, including optional service account impersonation. Set via [externalAccount].
     */
    EXTERNAL_ACCOUNT_CONFIG_FILE,

    /**
     * Load an [com.google.auth.oauth2.ExternalAccountCredentials] from the credential config JSON
     * payload referenced by [GcpBuildServiceParams.externalAccountConfigRef].
     *
     * The reference points to an environment variable or system property whose value is the full
     * credential config JSON string. Set via [externalAccount].
     */
    EXTERNAL_ACCOUNT_CONFIG_ENV,

    /**
     * Construct an [com.google.auth.oauth2.IdentityPoolCredentials] programmatically from a
     * pre-fetched OIDC token, a workload identity pool provider audience, and an optional service
     * account to impersonate.
     *
     * The OIDC token is resolved at execution time from [GcpBuildServiceParams.workloadIdentityTokenRef].
     * The audience is stored in [GcpBuildServiceParams.workloadIdentityAudience]. When
     * [GcpBuildServiceParams.workloadIdentityServiceAccountEmail] is set, service account impersonation
     * is configured automatically. Set via [workloadIdentity].
     */
    WORKLOAD_IDENTITY_OIDC,
}
