name: Build Gradle Tools
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      aggregate-jacoco-id: ${{ steps.upload-aggregate-jacoco.outputs.artifact-id }}
      aggregate-kdoc-id: ${{ steps.upload-aggregate-kdoc.outputs.artifact-id }}
      aggregate-test-id: ${{ steps.upload-aggregate-test.outputs.artifact-id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: Build
        run: ./gradlew --info --stacktrace :build
      - name: Upload Aggregate Test Report
        id: upload-aggregate-test
        uses: actions/upload-artifact@v4
        with:
          name: test-aggregate
          path: aggregation/testing/build/reports/tests/test/aggregated-results
      - name: Upload Aggregate KDoc
        id: upload-aggregate-kdoc
        uses: actions/upload-artifact@v4
        with:
          name: kdoc-aggregate
          path: aggregation/dokkatoo/build/dokka/html
      - name: Upload Aggregate JaCoCo Code Coverage Report
        id: upload-aggregate-jacoco
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-aggregate
          path: aggregation/jacoco/build/reports/jacoco/testCodeCoverageReport

  jacoco:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write

    steps:
      - name: Download Aggregate JaCoCo Code Coverage Artifact
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{needs.job1.outputs.aggregate-jacoco-id}}
      - name: Report JaCoCo
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: jacoco-aggregate/testCodeCoverageReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Aggregate Code Coverage
          update-comment: true
          # FIXME Remove after improvements are made
          min-coverage-overall: 0
          min-coverage-changed-files: 0
